
--http://www.xuanfengge.com/easeing/easeing/
Ease = {
    Unset = "Unset",
    Linear = "Linear",
    InSine = "InSine",
    OutSine = "OutSine",
    InOutSine = "InOutSine",
    InQuad = "InQuad",
    OutQuad = "OutQuad",
    InOutQuad = "InOutQuad",
    InCubic = "InCubic",
    OutCubic = "OutCubic",
    InOutCubic = "InOutCubic",
    InQuart = "InQuart",
    OutQuart = "OutQuart",
    InOutQuart = "InOutQuart",
    InQuint = "InQuint",
    OutQuint = "OutQuint",
    InOutQuint = "InOutQuint",
    InExpo = "InExpo",
    OutExpo = "OutExpo",
    InOutExpo = "InOutExpo",
    InCirc = "InCirc",
    OutCirc = "OutCirc",
    InOutCirc = "InOutCirc",
    InElastic = "InElastic",
    OutElastic = "OutElastic",
    InOutElastic = "InOutElastic",
    InBack = "InBack",
    OutBack = "OutBack",
    InOutBack = "InOutBack",
    InBounce = "InBounce",
    OutBounce = "OutBounce",
    InOutBounce = "InOutBounce",
    Flash = "Flash",
    InFlash = "InFlash",
    OutFlash = "OutFlash",
    InOutFlash = "InOutFlash",
    INTERNAL_Zero = "INTERNAL_Zero",
    INTERNAL_Custom = "INTERNAL_Custom",
}


