require("System.Define.LuaEnum")

require("System.Lang.Core.Class")
require("System.Lang.Core.Color")
require("System.Lang.Core.ConfigOptimizer")
require("System.Lang.Core.Coroutine")
require("System.Lang.Core.Delegate")
require("System.Lang.Core.Functions")
require("System.Lang.Core.Strict")
require("System.Lang.Core.String")
require("System.Lang.Core.Table")

require("System.Lang.Collection.Array")
require("System.Lang.Collection.Heap")
require("System.Lang.Collection.HeapHelper")
require("System.Lang.Collection.List")
require("System.Lang.Collection.Queue")
require("System.Lang.Collection.Set")
require("System.Lang.Collection.SimpleArray")
require("System.Lang.Collection.Stack")

require("System.Lang.Math.Math")
require("System.Lang.Math.Quaternion")
require("System.Lang.Math.Rect")
require("System.Lang.Math.Vector2")
require("System.Lang.Math.Vector3")
require("System.Lang.Math.Vector4")